### ISSUE TITLE
Implement a way to run all tests easily

### ISSUE THREAD

**Issue by albertoursino** [d-u-d-e/c-compiler#21]
I was also thinking to implement a _pre-commit Git hook_ for automatically running tests before every commit, so to fail the commit if any test fails. But since we will have lots of tests in the future, running all of them along with every commit is likely to become a costly operation that we don't want. 

I would rather suggest running them manually during a PR with the method we're going to create with this issue.

What do you think guys @CremaLuca @d-u-d-e @Fabio-Marangoni?

**Comment by d-u-d-e** [comment]
I agree.

**Comment by albertoursino** [comment]
In order to run all tests you have to use:

```Python
python3 -m unittest discover
```

Source: https://docs.python.org/3/library/unittest.html#test-discovery

With [this](https://github.com/d-u-d-e/c-compiler/pull/20/commits/79ee8271f2b01ddf1c8b1046d304593559377338) commit I added the `__init__` files in tests directories. They are necessary to the `discover` method. You also have to name all the test files as `test_*.py`.

**Comment by CremaLuca** [comment]
One should ideally commit as frequently as they like, if we force unit tests to pass to be able to commit you are preventing TDD from happening as one may not solve all the unit tests they have written before committing.
I prefer checking for unit tests when the pull request is opened, that's when the code should be squeaky clean
